#!/bin/sh

mkdir build

######## ENTER PATH TO YOUR JAVA, JAVAC AND JAR BINARIES HERE
export JAVA_HOME=/usr/local/lib/jdk-8u25
export _JAVA_OPTIONS=
export PATH=${JAVA_HOME}/bin:${PATH}

java="java"
javac="javac"
jar="jar"

echo "COMPILING JAVA CLASSES..."
$javac -d build `find . -name *.java`


cd build
if [ "$?" -eq "0" ]; then
	echo "BUILDING JAR FILE (with manifest)..."
	echo "Main-class: main.Main" > manifest.mf
	$jar cfm experiments.jar manifest.mf *
fi
echo "DONE."
